### ISSUE TITLE
Nice App but some bugs 

### ISSUE THREAD

**Issue by frankyxcs** [LucasJia/Note-and-Memo#1]
very nice app but after inserting an image in a note i'm getting this error here in logcat

seems there is a bug in the reminder too 

maybe you have time to fix this ?? thanx in advance
frank

here are the log :
com.lucas.notesoncloud E/CursorWindow: Failed to read row 0, column 1 from a CursorWindow which has 0 rows, 2 columns.
02-02 02:37:53.310 13429-13539/com.lucas.notesoncloud E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                        Process: com.lucas.notesoncloud, PID: 13429
                                                                        java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                            at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                            at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
                                                                         Caused by: java.lang.IllegalStateException: Couldn't read row 0, col 1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                            at android.database.CursorWindow.nativeGetBlob(Native Method)
                                                                            at android.database.CursorWindow.getBlob(CursorWindow.java:403)
                                                                            at android.database.AbstractWindowedCursor.getBlob(AbstractWindowedCursor.java:45)
                                                                            at android.database.CursorWrapper.getBlob(CursorWrapper.java:147)
                                                                            at com.lucas.notesoncloud.note.ImageTableOperator.get(ImageTableOperator.java:23)
                                                                            at com.lucas.notesoncloud.util.bitmaputil.BitmapSource.decodeFromDataBaseId(BitmapSource.java:118)
                                                                            at com.lucas.notesoncloud.util.bitmaputil.BitmapSource.decode(BitmapSource.java:54)
                                                                            at com.lucas.notesoncloud.util.bitmaputil.BitmapUtil.createBitmap(BitmapUtil.java:110)
                                                                            at com.lucas.notesoncloud.note.NoteContentParser.getFirstBitmap(NoteContentParser.java:113)
                                                                            at com.lucas.notesoncloud.note.holder.item.NoteItemViewHolder$1.doInBackground(NoteItemViewHolder.java:76)
                                                                            at com.lucas.notesoncloud.note.holder.item.NoteItemViewHolder$1.doInBackground(NoteItemViewHolder.java:73)
                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
02-02 02:37:59.090 13429-13437/com.lucas.notesoncloud W/CursorWrapperInner: Cursor finalized without prior close()

**Comment by LucasJia** [comment]
I store the image in the database, but the sqlite's maximum window size(config_cursorWindowSize) is 2M.
If one row exceeds this limit, you will get this error.

this is my log in warn level:
02-04 03:41:33.316 7405-7441/? W/CursorWindow: Window is full: requested allocation 2892154 bytes, free space 2096708 bytes, window size 2097152 bytes

Already fix up.

**Comment by frankyxcs** [comment]
HI again ! 

one suggestion : 
would be nice if you could add an share function to share a note text + image with another app  on viewing the note

if you have time 

greets frank

**Comment by LucasJia** [comment]
Hi frank, it's a very good suggestion, I have already add this share function to my app. 
You can long click image to share with another app on viewing(not editing) the note.
cheers.
